aws_region: ap-northeast-1
aws_vpc_id: vpc-3e1fc959
aws_keypair: bbrfkr-keypair-for-aws
aws_ami_id: ami-6be57d0d
aws_iam_role_for_ec2: &iam_role bbrfkr-role-for-ec2
aws_hosted_zone_id: ZMT06JP8KAKS7
aws_subnets:
- name: &subnet-iac bbrfkr-subnet-iac
  cidr: 192.168.100.0/24
  state: present
- name: &subnet-test bbrfkr-subnet-test
  cidr: 192.168.101.0/24
  state: present
- name: &subnet-prod bbrfkr-subnet-prod
  cidr: 192.168.102.0/24
  state: present
aws_groups:
- name: &sg-workstation bbrfkr-sg-workstation
  description: workstation
  state: present
  rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: icmp 
    from_port: -1
    to_port: -1
    cidr_ip: 192.168.0.0/16
- name: &sg-web bbrfkr-sg-web
  description: web
  state: present
  rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: 192.168.0.0/16
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: icmp 
    from_port: -1
    to_port: -1
    cidr_ip: 192.168.0.0/16
- name: &sg-jenkins bbrfkr-sg-jenkins
  description: jenkins
  state: present
  rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: 192.168.0.0/16
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 50000
    to_port: 50000
    cidr_ip: 192.168.0.0/16
  - proto: icmp 
    from_port: -1
    to_port: -1
    cidr_ip: 192.168.0.0/16
aws_instances:
- tags:
    Name: bbrfkr-instance-iac-jenkins
    Env: iac
  instance_type: t2.micro
  security_group: *sg-jenkins
  state: present
  iam_role: *iam_role
  vpc_subnet: *subnet-iac
  az: ap-northeast-1c
  assign_public_ip: yes
- tags:
    Name: bbrfkr-instance-test-blue
    Env: test
    Color: blue
  instance_type: t2.micro
  security_group: *sg-web
  state: present
  vpc_subnet: *subnet-test
  az: ap-northeast-1c
  assign_public_ip: yes
- tags:
    Name: bbrfkr-instance-test-green
    Env: test
    Color: green
  instance_type: t2.micro
  security_group: *sg-web
  state: present
  vpc_subnet: *subnet-test
  az: ap-northeast-1c
  assign_public_ip: yes
- tags:
    Name: bbrfkr-instance-prod-blue
    Env: prod
    Color: blue
  instance_type: t2.micro
  security_group: *sg-web
  state: present
  vpc_subnet: *subnet-prod
  az: ap-northeast-1c
  assign_public_ip: yes
- tags:
    Name: bbrfkr-instance-prod-green
    Env: prod
    Color: green
  instance_type: t2.micro
  security_group: *sg-web
  state: present 
  vpc_subnet: *subnet-prod
  az: ap-northeast-1c
  assign_public_ip: yes
