---
- block:
  - name: check subnet id
    ec2_vpc_subnet_facts:
      region: "{{ aws_region }}"
      filters:
        "tag:Name": "{{ item.vpc_subnet }}"
    register: reg_vpc_subnet
  - name: create instances
    ec2:
      region: "{{ aws_region }}"
      key_name: "{{ aws_keypair }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ aws_ami_id }}"
      group: "{{ item.security_group }}"
      vpc_subnet_id: "{{ reg_vpc_subnet.subnets.0.id }}"
      volumes: "{{ item.volumes | default(omit) }}"
      instance_tags:
        Name: "{{ item.name }}"
      count_tag:
        Name: "{{ item.name }}"
      exact_count: 1
      assign_public_ip: yes
  when: item.state == "present"
- block:
  - name: terminate instance
    ec2:
      region: "{{ aws_region }}"
      image: "dummy"
      count_tag:
        Name: "{{ item.name }}"
      exact_count: 0
  when: item.state == "absent"
