---
- name: manage instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - vars.yaml
  tasks:
  - include_tasks: include/manage_instance.yaml
    with_items: "{{ aws_instances }}"
