---
- name: manage subnets
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - vars/vars.yaml
  tasks:
  - name: manage subnets
    ec2_vpc_subnet:
      region: "{{ aws_region }}"
      state: "{{ item.state }}"
      vpc_id: "{{ aws_vpc_id }}"
      cidr: "{{ item.cidr }}"
      resource_tags:
        Name: "{{ item.name }}"
    with_items: "{{ aws_subnets }}"
    
