---
- name: wait for iac-jenkins up
  hosts: tag_Name_bbrfkr_instance_iac_jenkins
  gather_facts: false
  tasks:
  - name: wait for ssh port to be up
    wait_for:
      host: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
      port: 22
      state: started
    delegate_to: localhost

- name: wait for test env's instances up
  hosts: tag_Env_test
  gather_facts: false
  tasks:
  - name: wait for ssh port to be up
    wait_for:
      host: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
      port: 22
      state: started
    delegate_to: localhost

- name: wait for prod env's instances up
  hosts: tag_Env_prod
  gather_facts: false
  tasks:
  - name: wait for ssh port to be up
    wait_for:
      host: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
      port: 22
      state: started
    delegate_to: localhost
